// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Fruit struct {
	ID         int64            `json:"id"`
	Name       string           `json:"name"`
	Brand      pgtype.Text      `json:"brand"`
	PricePerKg pgtype.Numeric   `json:"price_per_kg"`
	StockKg    int32            `json:"stock_kg"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}
