// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateFruit(ctx context.Context, arg CreateFruitParams) (Fruit, error)
	DeleteFruit(ctx context.Context, id int64) error
	GetCheapFruits(ctx context.Context, pricePerKg pgtype.Numeric) ([]Fruit, error)
	GetFruit(ctx context.Context, id int64) (Fruit, error)
	ListFruits(ctx context.Context) ([]Fruit, error)
	UpdateFruitPrice(ctx context.Context, arg UpdateFruitPriceParams) (Fruit, error)
	UpdateFruitStock(ctx context.Context, arg UpdateFruitStockParams) (Fruit, error)
}

var _ Querier = (*Queries)(nil)
