// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFruit = `-- name: CreateFruit :one
INSERT INTO fruits (
    name, brand, price_per_kg, stock_kg
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, name, brand, price_per_kg, stock_kg, created_at, updated_at
`

type CreateFruitParams struct {
	Name       string         `json:"name"`
	Brand      pgtype.Text    `json:"brand"`
	PricePerKg pgtype.Numeric `json:"price_per_kg"`
	StockKg    int32          `json:"stock_kg"`
}

func (q *Queries) CreateFruit(ctx context.Context, arg CreateFruitParams) (Fruit, error) {
	row := q.db.QueryRow(ctx, createFruit,
		arg.Name,
		arg.Brand,
		arg.PricePerKg,
		arg.StockKg,
	)
	var i Fruit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.PricePerKg,
		&i.StockKg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFruit = `-- name: DeleteFruit :exec
DELETE FROM fruits
WHERE id = $1
`

func (q *Queries) DeleteFruit(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFruit, id)
	return err
}

const getCheapFruits = `-- name: GetCheapFruits :many
SELECT id, name, brand, price_per_kg, stock_kg, created_at, updated_at FROM fruits
WHERE price_per_kg < $1
ORDER BY price_per_kg ASC
`

func (q *Queries) GetCheapFruits(ctx context.Context, pricePerKg pgtype.Numeric) ([]Fruit, error) {
	rows, err := q.db.Query(ctx, getCheapFruits, pricePerKg)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fruit{}
	for rows.Next() {
		var i Fruit
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Brand,
			&i.PricePerKg,
			&i.StockKg,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFruit = `-- name: GetFruit :one
SELECT id, name, brand, price_per_kg, stock_kg, created_at, updated_at FROM fruits
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFruit(ctx context.Context, id int64) (Fruit, error) {
	row := q.db.QueryRow(ctx, getFruit, id)
	var i Fruit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.PricePerKg,
		&i.StockKg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFruits = `-- name: ListFruits :many
SELECT id, name, brand, price_per_kg, stock_kg, created_at, updated_at FROM fruits
ORDER BY name
`

func (q *Queries) ListFruits(ctx context.Context) ([]Fruit, error) {
	rows, err := q.db.Query(ctx, listFruits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fruit{}
	for rows.Next() {
		var i Fruit
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Brand,
			&i.PricePerKg,
			&i.StockKg,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFruitPrice = `-- name: UpdateFruitPrice :one
UPDATE fruits
SET price_per_kg = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, brand, price_per_kg, stock_kg, created_at, updated_at
`

type UpdateFruitPriceParams struct {
	ID         int64          `json:"id"`
	PricePerKg pgtype.Numeric `json:"price_per_kg"`
}

func (q *Queries) UpdateFruitPrice(ctx context.Context, arg UpdateFruitPriceParams) (Fruit, error) {
	row := q.db.QueryRow(ctx, updateFruitPrice, arg.ID, arg.PricePerKg)
	var i Fruit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.PricePerKg,
		&i.StockKg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFruitStock = `-- name: UpdateFruitStock :one
UPDATE fruits
SET stock_kg = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, brand, price_per_kg, stock_kg, created_at, updated_at
`

type UpdateFruitStockParams struct {
	ID      int64 `json:"id"`
	StockKg int32 `json:"stock_kg"`
}

func (q *Queries) UpdateFruitStock(ctx context.Context, arg UpdateFruitStockParams) (Fruit, error) {
	row := q.db.QueryRow(ctx, updateFruitStock, arg.ID, arg.StockKg)
	var i Fruit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.PricePerKg,
		&i.StockKg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
